export const baseURL: string = "https://zigoapi.stackearn.com/";
export const key: string = "";
export const projectName: string = "Zigo Live ";
export const apiKey: string =  "AIzaSyDpDATML_ff6R_vJrvDYgixMRgXBva_IzU";
export const authDomain : string =  "zigolive-7ba4e.firebaseapp.com";
export const projectId : string = "zigolive-7ba4e";
export const storageBucket : string = "zigolive-7ba4e.firebasestorage.app";
export const messagingSenderId : string = "609534297988";
export const appId : string = "1:609534297988:web:802aeaaa26a97daec2ffd1";
export const measurementId : string = "G-GRE04MYJWJ"